spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8
    username: root
    password: zzb200166
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.scheduler.instanceName: OrderService
      org.quartz.scheduler.instanceId: Order1
      org.quartz.jobStore.isClustered: true